// <auto-generated />
using LekeCozumleri.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LekeCozumleri.DataAccessLayer.Migrations
{
    [DbContext(typeof(LekeContext))]
    [Migration("20240313210129_initialize_mig2")]
    partial class initialize_mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LekeCozumleri.Entities.Concretes.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LekeCozumleri.Entities.Concretes.Stain", b =>
                {
                    b.Property<int>("StainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StainId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("StainDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StainId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Staines");
                });

            modelBuilder.Entity("LekeCozumleri.Entities.Concretes.Stain", b =>
                {
                    b.HasOne("LekeCozumleri.Entities.Concretes.Category", "category")
                        .WithMany("Stain")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("LekeCozumleri.Entities.Concretes.Category", b =>
                {
                    b.Navigation("Stain");
                });
#pragma warning restore 612, 618
        }
    }
}
